### ISSUE TITLE
Include links to graphs with different time ranges?

### ISSUE THREAD

**Issue by emschwartz** [fiberplane/autometrics-rs#23]
It might be useful to include links to the Prometheus graphs with different time ranges, like:

- Request Rate: [last hour](#), [day](#), [week](#)
- Error Rate: [last hour](#), [day](#), [week](#)
- ...

**Comment by keturiosakys** [comment]
I feel like, this might end up cramming too many links in a relatively small space (the hover window in the IDE). I feel like the main value for it is that it prefills the query in the Prometheus window - anyone can then shift the time window quite easily within the tool itself.

**Comment by emschwartz** [comment]
Mm that's a fair point

**Comment by emschwartz** [comment]
One argument for including those links is that you probably want to change both the overall time range and the window size. For example, using something like `[30m]` or `[1h]` instead of `[5m]` is probably better if you're looking at a whole day.

**Comment by IvanMerrill** [comment]
hmm, I'm not sure that they're going to be that useful tbh given as Laurynas says, you already have the queries there. It's easy to change the time window, and changing the window for the metric calculation to `[1h]` or greater reduces the quality of the data. It's fine for overall trends but you might miss spikes.
