### ISSUE TITLE
add some way to skip a function inside of a `#[autometrics]`'d `impl` block

### ISSUE THREAD

**Issue by mellowagain** [fiberplane/autometrics-rs#33]
while it is really convenient to just `#[autometrics]` a whole `impl` block, it is not always really *all* blocks one wants to audit. one example in this repo illustrates it very well:

```rust
#[autometrics]
impl Database {
    pub fn new() -> Self {
        Self
    }

    pub async fn load_details(&self) -> Result<(), ApiError> {
        // [...]
    }
}
```

here the `new()` function is very small and the compiler could even inline it, but by adding the `#[autometrics]` macro on top of it it'll add the metrics stuff and thus may even disqualify it from being inline'd and thus be a performance penalty.

something like this would be cool:

```rust
#[autometrics]
impl Database {
    #[skip_autometrics]
    pub fn new() -> Self {
        Self
    }

    pub async fn load_details(&self) -> Result<(), ApiError> {
        // [...]
    }
}
```

# workarounds

currently, it is possible to workaround this by just splitting it into two `impl` blocks:

```rust
impl Database {
    pub fn new() -> Self {
        Self
    }
}

#[autometrics]
impl Database {
    pub async fn load_details(&self) -> Result<(), ApiError> {
        // [...]
    }
}
```

<small>internal ref: [slack chat with evan](https://fiberplane.slack.com/archives/D03HQ2A6LS1/p1675952039427779)</small>

**Comment by emschwartz** [comment]
I really like this suggestion.

One thing that's a bit annoying is that I think `skip_autometrics` would need to be a separate proc macro that you'd need to import. The ability for macros to work on additional attributes is [limited to derive macros](https://doc.rust-lang.org/reference/procedural-macros.html#derive-macro-helper-attributes).

A bit of a silly workaround would be to simply call the macro `skip` so if you didn't separately import it, you would add `#[autometrics::skip]` to your function.
